"""empty message

Revision ID: 1926a37a204b
Revises: f889554af078
Create Date: 2024-04-15 15:55:51.857733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1926a37a204b'
down_revision = 'f889554af078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'languages', ['learning_language_id'], ['id'])
        batch_op.create_foreign_key(None, 'languages', ['native_language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('languages')
    # ### end Alembic commands ###
