"""empty message

Revision ID: 3378b8237b87
Revises: 62f7c57e79a2
Create Date: 2024-04-21 18:30:45.420128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3378b8237b87'
down_revision = '62f7c57e79a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_course_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('modules_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'available_courses', ['available_course_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('modules_course_id_fkey', 'courses', ['course_id'], ['id'])
        batch_op.drop_column('available_course_id')

    # ### end Alembic commands ###
