"""empty message

Revision ID: 62f7c57e79a2
Revises: 8b8d0b2e4813
Create Date: 2024-04-21 17:37:40.398534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f7c57e79a2'
down_revision = '8b8d0b2e4813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_course_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('courses_course_language_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'available_courses', ['available_course_id'], ['id'])
        batch_op.drop_column('course_language_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_language_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('courses_course_language_id_fkey', 'languages', ['course_language_id'], ['id'])
        batch_op.drop_column('available_course_id')

    # ### end Alembic commands ###
