"""empty message

Revision ID: 8b8d0b2e4813
Revises: 2f95287fa21d
Create Date: 2024-04-21 17:34:54.217291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8d0b2e4813'
down_revision = '2f95287fa21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('available_courses_language_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'languages', ['language_id'], ['id'])
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('available_courses_language_fkey', 'languages', ['language'], ['id'])
        batch_op.drop_column('language_id')

    # ### end Alembic commands ###
