"""empty message

Revision ID: a0729c9c4d01
Revises: 3378b8237b87
Create Date: 2024-04-23 02:23:54.710105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0729c9c4d01'
down_revision = '3378b8237b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lives', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_wrong', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_wrong')
        batch_op.drop_column('lives')

    # ### end Alembic commands ###
