"""empty message

Revision ID: a947956d703b
Revises: c1641ae1e6fc
Create Date: 2024-04-12 04:36:06.879860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a947956d703b'
down_revision = 'c1641ae1e6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idioms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idiom_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idiom_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('learning_language_id', sa.Integer(), nullable=True),
    sa.Column('native_language_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['learning_language_id'], ['idioms.id'], ),
    sa.ForeignKeyConstraint(['native_language_id'], ['idioms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_table('idiom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idiom',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idiom_pkey'),
    sa.UniqueConstraint('name', name='idiom_name_key')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('native_language', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('target_language', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('users')
    op.drop_table('idioms')
    # ### end Alembic commands ###
